<?php

/**
 * @file
 * Install, update, and uninstall functions for the Bot module.
 */

/**
 * Implements hook_uninstall().
 */
function bot_uninstall() {
  variable_del('bot_auto_retry');
  variable_del('bot_auto_reconnect');
  variable_del('bot_cache_cleared');
  variable_del('bot_channels');
  variable_del('bot_debugging');
  variable_del('bot_nickname');
  variable_del('bot_password');
  variable_del('bot_server');
  variable_del('bot_server_port');
}
