<?php
// $Id$

/**
 * @file
 * A plugin that reports version numbers for various components.
 */

/**
 * Implementation of hook_help().
 */
function bot_version_help($section) {
  switch ($section) {
    case 'nothing/here/yet':
      return 'nothing/here/yet/I/said/jeez!';
  }
}

/**
 * Implementation of hook_menu().
 */
function bot_version_menu($may_cache) {
  $items = array();

  if ($may_cache) {

  }
  else {

  }

  return $items;
}

function bot_version_irc_msg_channel($data) {
  bot_message('CHANNEL', $data->channel, $data->nick.': whee, zomg, it worked!');
}
